language: generic
sudo: require
services:
  - docker


before_install:
  - docker build -t asheesh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asheesh/docker-react npm run test

